//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCIScheduler.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservID { get; set; }
        public string ReservTime { get; set; }
        public string ReservDate { get; set; }
        public string RoomNumber { get; set; }
        public string UserID { get; set; }
        public int UserUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Room Room { get; set; }
    }
}
